version: 2.1
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.12 /usr/local/share/virtualenvs/tap-pipedrive
            source /usr/local/share/virtualenvs/tap-pipedrive/bin/activate
            uv pip install .[dev]
      - run:
          name: 'Unit Tests & Coverage Run'
          command: |
            source /usr/local/share/virtualenvs/tap-pipedrive/bin/activate
            uv pip install pytest coverage
            coverage run -m pytest tests/unittests
      - run:
          name: 'Coverage Report'
          command: |
            source /usr/local/share/virtualenvs/tap-pipedrive/bin/activate
            coverage report -m | tee coverage.txt
            coverage html
            echo "Coverage summary:"
            cat coverage.txt
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov
      - store_artifacts:
          path: coverage.txt
      - add_ssh_keys
      - run:
          name: 'Mocked Integration Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-pipedrive/bin/activate
            uv pip install pytest
            pytest tests/mockedtests

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 14 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
